MAX_ATTRIBUTE_RANK = 10

MAX_CRIT_CHANCE = 0.45
MAX_DODGE_CHANCE = 0.35
MAX_CRITICAL_DAMAGE_MULTIPLIER = 2.75

VALOR_DAMAGE_PER_STEP = 1
VALOR_CRITICAL_DAMAGE_PER_RANK = 0.05
VALOR_HEALTH_PER_TWO_RANKS = 1

INSTINCT_CRIT_CHANCE_PER_RANK = 0.04
INSTINCT_DODGE_CHANCE_PER_RANK = 0.03

WILL_CRIT_CHANCE_PER_RANK = 0.01
WILL_CRITICAL_DAMAGE_PER_RANK = 0.03

FORTITUDE_HEALTH_PER_RANK = 2
FORTITUDE_DODGE_CHANCE_PER_RANK = 0.01
