from settings import (
    ARCHER_COLOR,
    BRUTE_COLOR,
    ENEMY_COLOR,
    ORACLE_COLOR,
    SLEEPING_ARCHER_COLOR,
    SLEEPING_BRUTE_COLOR,
    SLEEPING_ENEMY_COLOR,
    SLEEPING_ORACLE_COLOR,
    SLEEPING_PRIEST_COLOR,
    SLEEPING_SENTINEL_COLOR,
    SLEEPING_WARDEN_COLOR,
    PRIEST_COLOR,
    SENTINEL_COLOR,
    WARDEN_COLOR,
    PRIEST_GHOST_COLOR,
    SLEEPING_PRIEST_GHOST_COLOR,
    MIMIC_COLOR,
    SLEEPING_MIMIC_COLOR,
)


ENEMY_TYPES = {
    "goblin": {
        "display_name": "Goblin",
        "max_health": 4,
        "aggro_radius": 5,
        "wander_chance": 0.35,
        "move_every": 1,
        "attack_kind": "melee",
        "attack_range": 1,
        "damage_by_mode": {
            "melee": ((1, 2, 3), (75, 20, 5)),
        },
        "color": ENEMY_COLOR,
        "sleeping_color": SLEEPING_ENEMY_COLOR,
        "retreat_jump_chance": 0.0,
        "dodge_chance": 0.15,
    },
    "mimic": {
        "display_name": "Mimic",
        "max_health": 9,
        "aggro_radius": 99,
        "wander_chance": 0.0,
        "move_every": 1,
        "attack_kind": "melee",
        "attack_range": 1,
        "damage_by_mode": {
            "melee": ((2, 3), (75, 25)),
        },
        "color": MIMIC_COLOR,
        "sleeping_color": SLEEPING_MIMIC_COLOR,
        "retreat_jump_chance": 0.0,
        "dodge_chance": 0.0,
    },
    "brute": {
        "display_name": "Brute",
        "max_health": 8,
        "aggro_radius": 4,
        "wander_chance": 0.15,
        "move_every": 2,
        "attack_kind": "cleave",
        "attack_range": 2,
        "damage_by_mode": {
            "cleave": ((2, 3), (80, 20)),
        },
        "color": BRUTE_COLOR,
        "sleeping_color": SLEEPING_BRUTE_COLOR,
        "retreat_jump_chance": 0.0,
        "dodge_chance": 0.0,
    },
    "archer": {
        "display_name": "Archer",
        "max_health": 4,
        "aggro_radius": 10,
        "wander_chance": 0.25,
        "move_every": 1,
        "attack_kind": "ranged",
        "attack_range": 10,
        "damage_by_mode": {
            "ranged": ((3,), (1,)),
            "melee": ((1,), (1,)),
        },
        "color": ARCHER_COLOR,
        "sleeping_color": SLEEPING_ARCHER_COLOR,
        "retreat_jump_chance": 0.35,
        "dodge_chance": 0.15,
    },
    "sentinel": {
        "display_name": "Sentinel",
        "max_health": 9,
        "aggro_radius": 6,
        "wander_chance": 0.10,
        "move_every": 2,
        "attack_kind": "melee",
        "attack_range": 1,
        "damage_by_mode": {
            "melee": ((2, 3), (75, 25)),
        },
        "color": SENTINEL_COLOR,
        "sleeping_color": SLEEPING_SENTINEL_COLOR,
        "retreat_jump_chance": 0.0,
        "dodge_chance": 0.0,
        "shield_duration": 3,
        "shield_cooldown": 2,
    },
    "priest": {
        "display_name": "Grave Priest",
        "max_health": 5,
        "aggro_radius": 7,
        "wander_chance": 0.20,
        "move_every": 1,
        "attack_kind": "priest_magic",
        "attack_range": 4,
        "damage_by_mode": {
            "magic": ((1, 2), (70, 30)),
            "melee": ((1,), (1,)),
        },
        "color": PRIEST_COLOR,
        "sleeping_color": SLEEPING_PRIEST_COLOR,
        "retreat_jump_chance": 0.0,
        "dodge_chance": 0.0,
        "heal_amount": 2,
        "heal_cooldown": 3,
        "heal_range": 6,
        "death_spawn": {
            "enemy_type": "priest_ghost",
            "chance": 0.60,
            "starts_aggro": True,
            "message": "The Grave Priest's spirit rises from its corpse!",
        },
    },
    "priest_ghost": {
        "display_name": "Priest Ghost",
        "max_health": 6,
        "aggro_radius": 99,
        "wander_chance": 0.0,
        "move_every": 1,
        "attack_kind": "priest_magic",
        "attack_range": 4,
        "damage_by_mode": {
            "magic": ((3, 4), (70, 30)),
            "melee": ((2,), (1,)),
        },
        "color": PRIEST_GHOST_COLOR,
        "sleeping_color": SLEEPING_PRIEST_GHOST_COLOR,
        "retreat_jump_chance": 0.0,
        "dodge_chance": 0.60,
    },
    "warden": {
        "display_name": "Crypt Warden",
        "max_health": 20,
        "aggro_radius": 12,
        "wander_chance": 0.0,
        "move_every": 1,
        "attack_kind": "boss",
        "attack_range": 7,
        "damage_by_mode": {
            "cross": ((2, 3), (80, 20)),
            "sweep": ((2, 3), (70, 30)),
            "runes": ((3,), (1,)),
        },
        "color": WARDEN_COLOR,
        "sleeping_color": SLEEPING_WARDEN_COLOR,
        "retreat_jump_chance": 0.0,
        "is_unique": True,
    },
    "oracle": {
        "display_name": "Oracle",
        "max_health": 48,
        "aggro_radius": 99,
        "wander_chance": 0.0,
        "move_every": 1,
        "attack_kind": "oracle",
        "attack_range": 99,
        "damage_by_mode": {
            "gaze": ((5, 6), (70, 30)),
            "revelation": ((5, 6), (60, 40)),
            "shockwave": ((3, 4), (75, 25)),
        },
        "phase_two_damage_by_mode": {
            "gaze": ((7, 8), (60, 40)),
            "revelation": ((7, 8), (50, 50)),
            "shockwave": ((4, 5), (75, 25)),
        },
        "color": ORACLE_COLOR,
        "sleeping_color": SLEEPING_ORACLE_COLOR,
        "retreat_jump_chance": 0.0,
        "is_unique": True,
        "is_immobile": True,
        "footprint_width": 3,
        "footprint_height": 3,
        "projectile_cooldown": 1,
    },
}
