FLOOR_CONFIGS = [
    {
        "act": 1,
        "act_floor": 1,
        "room_count": 4,
        "enemy_types": ["goblin", "goblin"],
        "chest_count": 0,
        "potion_count": 2,
    },
    {
        "act": 1,
        "act_floor": 2,
        "room_count": 6,
        "enemy_types": ["goblin", "goblin", "brute"],
        "chest_count": 0,
        "potion_count": 2,
    },
    {
        "act": 1,
        "act_floor": 3,
        "room_count": 0,
        "boss_room_layout": "warden_arena",
        "enemy_types": ["goblin", "brute", "goblin"],
        "boss_enemy_types": ["warden", "archer", "archer"],
        "chest_count": 0,
        "potion_count": 2,
    },
    {
        "act": 2,
        "act_floor": 1,
        "map_columns": 43,
        "map_rows": 27,
        "room_count": 10,
        "generation_attempts": 12,
        "minimum_start_exit_distance": 24,
        "secret_room_chance": 0.75,
        "treasury_room": True,
        "rune_room": True,
        "trader": True,
        "bloody_altar_near_trader": True,
        "spike_trap_count": 5,
        "breakable_crate_count": 7,
        "enemy_counts": {
            "goblin": 2,
            "brute": 3,
            "archer": 2,
            "sentinel": 2,
            "priest": 2,
        },
        "chest_count": 2,
        "mimic_count": 1,
        "potion_count": 0,
    },
    {
        "act": 2,
        "act_floor": 2,
        "bloody_altar": True,
        "map_columns": 47,
        "map_rows": 29,
        "room_count": 12,
        "generation_attempts": 12,
        "minimum_start_exit_distance": 28,
        "secret_room_chance": 1.0,
        "treasury_room": True,
        "spike_trap_count": 7,
        "breakable_crate_count": 9,
        "enemy_counts": {
            "goblin": 5,
            "brute": 4,
            "archer": 4,
            "sentinel": 4,
            "priest": 3,
        },
        "chest_count": 2,
        "mimic_count": 1,
        "potion_count": 0,
    },
    {
        "act": 2,
        "act_floor": 3,
        "map_columns": 55,
        "map_rows": 35,
        "room_count": 15,
        "generation_attempts": 12,
        "minimum_start_exit_distance": 34,
        "secret_room_chance": 1.0,
        "treasury_room": True,
        "spike_trap_count": 7,
        "breakable_crate_count": 9,
        "enemy_counts": {
            "goblin": 6,
            "brute": 5,
            "archer": 5,
            "sentinel": 4,
            "priest": 4,
        },
        "chest_count": 2,
        "mimic_count": 1,
        "potion_count": 0,
    },
    {
        "act": 2,
        "act_floor": 4,
        "room_count": 0,
        "enemy_types": [],
        "boss_enemy_types": ["oracle"],
        "boss_room_width": 19,
        "boss_room_height": 13,
        "boss_room_layout": "oracle_arena",
        "seal_boss_door_during_fight": True,
        "chest_count": 0,
        "potion_count": 0,
        "breakable_crate_count": 0,
    },
    {
        "act": 3,
        "act_floor": 1,
        "map_path": (
            "assets/maps/act_3/environment_v1/"
            "room_spawn_01.tmx"
        ),
        "room_template_directory": (
            "assets/maps/act_3/environment_v1"
        ),
        "generated_piece_count": 5,
    },
]
