FLOOR_CONFIGS = [
    {
        "act": 1,
        "act_floor": 1,
        "room_count": 4,
        "enemy_types": ["goblin", "goblin"],
        "chest_count": 1,
        "potion_count": 1,
    },
    {
        "act": 1,
        "act_floor": 2,
        "room_count": 6,
        "enemy_types": ["goblin", "goblin", "brute"],
        "chest_count": 1,
        "potion_count": 1,
    },
    {
        "act": 1,
        "act_floor": 3,
        "room_count": 5,
        "enemy_types": ["goblin", "brute"],
        "boss_enemy_types": ["warden", "archer", "archer"],
        "chest_count": 1,
        "potion_count": 2,
    },
    {
        "act": 2,
        "act_floor": 1,
        "room_count": 6,
        "enemy_types": ["goblin", "brute", "archer", "archer"],
        "chest_count": 1,
        "potion_count": 2,
    },
    {
        "act": 2,
        "act_floor": 2,
        "room_count": 7,
        "enemy_types": [
            "goblin",
            "goblin",
            "brute",
            "archer",
            "archer",
        ],
        "chest_count": 2,
        "potion_count": 2,
    },
    {
        "act": 2,
        "act_floor": 3,
        "room_count": 7,
        "enemy_types": [
            "goblin",
            "brute",
            "brute",
            "archer",
            "archer",
            "archer",
        ],
        "chest_count": 2,
        "potion_count": 2,
    },
]
