GAME_WIDTH = 1280
GAME_HEIGHT = 720
INITIAL_WINDOW_SCALE = 1.25
FPS = 60
TILE_SIZE = 32
MAP_COLUMNS = 25
MAP_ROWS = 15

BACKGROUND_COLOR = (15, 12, 18)
FLOOR_COLOR = (52, 48, 55)
WALL_COLOR = (91, 82, 88)
GRID_COLOR = (38, 34, 41)
PLAYER_COLOR = (235, 235, 230)
ENEMY_COLOR = (165, 55, 62)
SLEEPING_ENEMY_COLOR = (95, 62, 68)
BRUTE_COLOR = (145, 82, 48)
SLEEPING_BRUTE_COLOR = (88, 65, 52)
ARCHER_COLOR = (75, 135, 105)
SLEEPING_ARCHER_COLOR = (55, 82, 70)
WARDEN_COLOR = (135, 80, 165)
SLEEPING_WARDEN_COLOR = (80, 58, 92)
SENTINEL_COLOR = (115, 125, 138)
SLEEPING_SENTINEL_COLOR = (68, 73, 82)
PRIEST_COLOR = (105, 165, 120)
SLEEPING_PRIEST_COLOR = (62, 92, 70)
ORACLE_COLOR = (95, 155, 215)
SLEEPING_ORACLE_COLOR = (70, 75, 86)
POTION_COLOR = (75, 180, 125)
KEY_COLOR = (230, 195, 75)
GOLD_COLOR = (245, 184, 45)
CHEST_COLOR = (125, 78, 43)
CHEST_BAND_COLOR = (185, 135, 65)
OPEN_CHEST_COLOR = (75, 50, 38)
LOCKED_COLOR = (80, 75, 82)
STAIRS_COLOR = (190, 170, 125)
TEXT_COLOR = (225, 218, 205)
HEALTH_BAR_BACKGROUND = (45, 25, 30)
HEALTH_BAR_COLOR = (200, 65, 75)
PLAYER_HEALTH_BAR_COLOR = (215, 175, 75)
DANGER_TILE_COLOR = (105, 35, 43)
DANGER_BORDER_COLOR = (225, 70, 78)
PLAYER_ATTACK_TILE_COLOR = (105, 82, 32)
PLAYER_ATTACK_BORDER_COLOR = (235, 190, 70)
ATTACK_WARNING_COLOR = (245, 210, 75)
PANEL_COLOR = (26, 23, 29)
PANEL_BORDER_COLOR = (74, 67, 78)

POTION_HEALING = 4
COMBAT_LOG_LIMIT = 5

# Core attributes. Keep the values here deliberately boring and editable:
# acts decide the starting ranks, while these constants define what a rank does.
STRENGTH_DAMAGE_PER_RANK = 1
DEXTERITY_CRIT_CHANCE_PER_RANK = 0.05
DEXTERITY_DODGE_CHANCE_PER_RANK = 0.05
DEXTERITY_CRITICAL_DAMAGE_PER_RANK = 0.10
INTELLIGENCE_SPELL_POWER_PER_RANK = 1
VITALITY_HEALTH_PER_RANK = 2
MAX_CRIT_CHANCE = 0.50
MAX_DODGE_CHANCE = 0.40
CRITICAL_DAMAGE_MULTIPLIER = 2.0
MAX_ATTRIBUTE_RANK = 10

# Temporary compatibility values for the Act Two upgrade screen. That screen is
# migrated separately; new shared progression must use the constants above.
HEALTH_UPGRADE_AMOUNT = VITALITY_HEALTH_PER_RANK
DAMAGE_UPGRADE_AMOUNT = STRENGTH_DAMAGE_PER_RANK
CRIT_UPGRADE_AMOUNT = DEXTERITY_CRIT_CHANCE_PER_RANK
DODGE_UPGRADE_AMOUNT = DEXTERITY_DODGE_CHANCE_PER_RANK

CLASS_ABILITY_KILLS = 2

# Assassin
ROGUE_INVISIBILITY_TURNS = 5
ASSASSIN_INVISIBILITY_TURNS = 15
ASSASSIN_TELEPORT_CHARGES = 3
ASSASSIN_ULTIMATE_CHARGES = 8
ASSASSIN_ULTIMATE_PRELUDE_MS = 620
ASSASSIN_ULTIMATE_STEP_MS = 430
ASSASSIN_ULTIMATE_OUTRO_MS = 360

# Archer
ARCHER_BASIC_ATTACK_RANGE = 2
ARCHER_BASIC_DAMAGE_MIN = 1
ARCHER_BASIC_DAMAGE_MAX = 2
ARCHER_EMPOWERED_SHOT_CHARGES = 3
ARCHER_EMPOWERED_SHOT_DAMAGE_MIN = 3
ARCHER_EMPOWERED_SHOT_DAMAGE_MAX = 5
ARCHER_EMPOWERED_SHOT_PROJECTILE_MS = 260
ARCHER_LEAP_CHARGES = 3
ARCHER_LEAP_RANGE = 3
ARCHER_LEAP_DURATION_MS = 320
ARCHER_BARRAGE_ZONE_CHARGES = 8
ARCHER_BARRAGE_ZONE_SIZE = 5

# Berserker
BERSERKER_RAGE_INJURED_HEALTH_RATIO = 0.50
BERSERKER_RAGE_CRITICAL_HEALTH_RATIO = 0.25
BERSERKER_RAGE_INJURED_DAMAGE_MULTIPLIER = 1.25
BERSERKER_RAGE_CRITICAL_DAMAGE_MULTIPLIER = 1.50
BERSERKER_CRUSHING_LEAP_CHARGES = 3
BERSERKER_CRUSHING_LEAP_RANGE = 5
BERSERKER_CRUSHING_LEAP_TRAVEL_MS = 360
BERSERKER_CRUSHING_LEAP_IMPACT_MS = 500
BERSERKER_LAST_RAGE_CHARGES = 8
BERSERKER_LAST_RAGE_TURNS = 10

#Paladin
PALADIN_HOLY_HAND_CHARGES = 3
PALADIN_HOLY_HAND_HEALING = 4
PALADIN_HOLY_HAND_EFFECT_MS = 650
PALADIN_SHIELD_CHARGE_CHARGES = 4
PALADIN_SHIELD_CHARGE_RANGE = 6
PALADIN_SHIELD_CHARGE_TRAVEL_MS = 420
PALADIN_HOLY_SHIELD_CHARGES = 8
PALADIN_HOLY_SHIELD_TURNS = 8
PALADIN_HOLY_SHIELD_DAMAGE_BONUS = 2
PALADIN_HOLY_SHIELD_HEALING_PER_HIT = 1

# Warlock
WARLOCK_BASIC_ATTACK_RANGE = 2
WARLOCK_BASIC_DAMAGE_MIN = 1
WARLOCK_BASIC_DAMAGE_MAX = 2
WARLOCK_DEMON_FORM_HEALTH_DRAIN = 1
WARLOCK_DEMON_FORM_DAMAGE_MULTIPLIER = 1.75
WARLOCK_CURSE_CHARGES = 3
WARLOCK_CURSE_TURNS = 10
WARLOCK_CURSE_RANGE = 5
WARLOCK_CURSE_DAMAGE_MULTIPLIER = 1.50
WARLOCK_SOUL_EXCHANGE_CHARGES = 4
WARLOCK_SOUL_EXCHANGE_RANGE = 5
WARLOCK_SOUL_EXCHANGE_TRAVEL_MS = 460

# Summoner
SUMMONER_FAMILIAR_CHARGES = 3
SUMMONER_ATTACK_RANGE = 2
SUMMONER_ATTACK_RANGE_WITH_FAMILIAR = 1
SUMMONER_BOND_CHARGES = 3
SUMMONER_BOND_DAMAGE_BONUS = 2
SUMMONER_TRUE_FORM_CHARGES = 5
SUMMONER_TRUE_FORM_HEALTH_BONUS = 8
SUMMONER_TRUE_FORM_DAMAGE_BONUS = 3

# Others
WARRIOR_STRIKE_DAMAGE_BONUS = 2
