SPHERE_DAMAGE = 4
LINE_DAMAGE = 4
BLACKFIRE_CONTACT_DAMAGE = 3
BLACKFIRE_EXPLOSION_DAMAGE = 6
RADIAL_DAMAGE = 10

LINE_CAST_CHANCE = 0.34
RADIAL_CAST_CHANCE = 0.45
RADIAL_COOLDOWN_TURNS = 4
CLOSE_RANGE_GRACE_TURNS = 1

POST_ATTACK_RECOVERY_TURNS = 0
BLACKFIRE_TURNS = 2
RADIAL_FIRE_CELLS = 8

ATTACK_REACTION_MS = 260
SPHERE_FLIGHT_MS = 420
LINE_FLIGHT_MS = 560
RADIAL_FLIGHT_MS = 760
IMPACT_MS = 320
WARNING_LOCK_MS = 300

PHASE_TWO_PRIMARY_DAMAGE = 5
PHASE_TWO_SECONDARY_DAMAGE = 6
PHASE_TWO_HAZARD_DAMAGE = 2
PHASE_TWO_HAZARD_TURNS = 2
PHASE_TWO_HAZARD_CELLS = 5

PHASE_TWO_TELEPORT_CHANCE = 0.82
PHASE_TWO_TELEPORT_MS = 360
PHASE_TWO_IMPACT_MS = 360
PHASE_TWO_PILLAR_BREAK_MS = 480
PHASE_TWO_PILLAR_HINT_MS = 700
PHASE_TWO_BLACKFIRE_CHANCE = 0.7
PHASE_TWO_RECOVERY_INTERVAL = 2

PHASE_TWO_LINE_DAMAGE = 7
PHASE_TWO_CHAOS_PATHS = 2
PHASE_TWO_CHAOS_BRANCH_CHANCE = 0.30
PHASE_TWO_ATTACK_SEQUENCE = (
    "single",
    "double",
)
