from pathlib import Path

from settings import (
    GAME_HEIGHT,
    GAME_WIDTH,
    MAP_COLUMNS,
    MAP_ROWS,
    TILE_SIZE,
)


MAP_WIDTH = MAP_COLUMNS * TILE_SIZE
MAP_HEIGHT = MAP_ROWS * TILE_SIZE
MAP_OFFSET_X = 40
MAP_OFFSET_Y = (GAME_HEIGHT - MAP_HEIGHT) // 2
SIDEBAR_X = MAP_OFFSET_X + MAP_WIDTH + 40
SIDEBAR_Y = MAP_OFFSET_Y
SIDEBAR_WIDTH = GAME_WIDTH - SIDEBAR_X - 40
SIDEBAR_HEIGHT = MAP_HEIGHT

PROJECT_ROOT = Path(__file__).resolve().parent.parent
ASSET_ROOT = PROJECT_ROOT / "assets" / "sprites"
FONT_ROOT = PROJECT_ROOT / "assets" / "fonts"

AWAKENING_OPEN_START_MS = 300
AWAKENING_OPEN_END_MS = 1500
AWAKENING_HOLD_END_MS = 2500
AWAKENING_FADE_END_MS = 3100
CLASS_SELECTION_READY_MS = 6600
