from pathlib import Path

from settings import (
    GAME_HEIGHT,
    GAME_WIDTH,
    MAP_COLUMNS,
    MAP_ROWS,
    TILE_SIZE,
)
from acts.act_two.presentation.awakening_timing import (
    AWAKENING_OPEN_START_MS,
    AWAKENING_OPEN_END_MS,
    AWAKENING_HOLD_END_MS,
    AWAKENING_FADE_END_MS,
    AWAKENING_SECOND_OPEN_START_MS,
    AWAKENING_SECOND_OPEN_END_MS,
    AWAKENING_RECOVERY_BLINK_START_MS,
    AWAKENING_RECOVERY_BLINK_END_MS,
    AWAKENING_OLD_MAN_APPROACH_START_MS,
    AWAKENING_OLD_MAN_APPROACH_END_MS,
    AWAKENING_DIALOGUE_START_MS,
    CLASS_SELECTION_READY_MS,
    CLASS_SELECTION_CHOICE_END_MS,
)

MAP_WIDTH = MAP_COLUMNS * TILE_SIZE
MAP_HEIGHT = MAP_ROWS * TILE_SIZE
MAP_OFFSET_X = 40
MAP_OFFSET_Y = (GAME_HEIGHT - MAP_HEIGHT) // 2
ACT_ONE_VIEW_OFFSET_X = (GAME_WIDTH - MAP_WIDTH) // 2 - MAP_OFFSET_X
SIDEBAR_X = MAP_OFFSET_X + MAP_WIDTH + 40
SIDEBAR_Y = MAP_OFFSET_Y
SIDEBAR_WIDTH = GAME_WIDTH - SIDEBAR_X - 40
SIDEBAR_HEIGHT = MAP_HEIGHT

ACT_TWO_VIEW_X = 0
ACT_TWO_VIEW_Y = 0
ACT_TWO_VIEW_WIDTH = GAME_WIDTH
ACT_TWO_VIEW_HEIGHT = GAME_HEIGHT

PROJECT_ROOT = Path(__file__).resolve().parent.parent
ASSET_ROOT = PROJECT_ROOT / "assets" / "sprites"
FONT_ROOT = PROJECT_ROOT / "assets" / "fonts"
AUDIO_ROOT = PROJECT_ROOT / "assets" / "audio"
ACT_ONE_SOUNDS_PATH = AUDIO_ROOT / "sounds_act_1"
ACT_TWO_SOUNDS_PATH = AUDIO_ROOT / "sounds_act_2"
MUSIC_ROOT = AUDIO_ROOT / "music"
ACT_ONE_MENU_MUSIC_PATH = MUSIC_ROOT / "act_1_menu.mp3"
ACT_ONE_MUSIC_PATH = MUSIC_ROOT / "act_1_music.mp3"
ACT_ONE_WARDEN_MUSIC_PATH = MUSIC_ROOT / "act_1_warden.mp3"
ACT_TWO_MENU_MUSIC_PATH = MUSIC_ROOT / "act_2_menu.mp3"
ACT_TWO_MUSIC_PATH = MUSIC_ROOT / "act_2_music.mp3"
ACT_THREE_MUSIC_PATH = MUSIC_ROOT / "act_3.mp3"

ACT_THREE_TILE_SIZE = 72
ACT_THREE_VIEW_X = 0
ACT_THREE_VIEW_Y = 0
ACT_THREE_VIEW_WIDTH = GAME_WIDTH
ACT_THREE_VIEW_HEIGHT = GAME_HEIGHT
ACT_THREE_BOTTOM_BAR_X = 0
ACT_THREE_BOTTOM_BAR_Y = 624
ACT_THREE_BOTTOM_BAR_WIDTH = GAME_WIDTH
ACT_THREE_BOTTOM_BAR_HEIGHT = 88
ACT_THREE_FRAME_X = 8
ACT_THREE_FRAME_Y = 32
ACT_THREE_SIDEBAR_X = GAME_WIDTH - 70
ACT_THREE_SIDEBAR_Y = 0
ACT_THREE_SIDEBAR_WIDTH = 70
ACT_THREE_SIDEBAR_HEIGHT = 720

ACT_THREE_NARRATIVE_START_MS = 450
ACT_THREE_NARRATIVE_READY_MS = 10800
ACT_THREE_EYES_OPEN_START_MS = 500
ACT_THREE_EYES_OPEN_END_MS = 2400
ACT_THREE_CAMERA_END_MS = 4800
ACT_THREE_HANDS_RISE_START_MS = 3000
ACT_THREE_HANDS_RISE_END_MS = 6500
ACT_THREE_HANDS_HOLD_END_MS = 8500
ACT_THREE_CLENCH_END_MS = 9700
ACT_THREE_FINAL_HOLD_END_MS = 12800
ACT_THREE_AWAKENING_END_MS = 14500
