from pathlib import Path

from settings import (
    GAME_HEIGHT,
    GAME_WIDTH,
    MAP_COLUMNS,
    MAP_ROWS,
    TILE_SIZE,
)


MAP_WIDTH = MAP_COLUMNS * TILE_SIZE
MAP_HEIGHT = MAP_ROWS * TILE_SIZE
MAP_OFFSET_X = 40
MAP_OFFSET_Y = (GAME_HEIGHT - MAP_HEIGHT) // 2
SIDEBAR_X = MAP_OFFSET_X + MAP_WIDTH + 40
SIDEBAR_Y = MAP_OFFSET_Y
SIDEBAR_WIDTH = GAME_WIDTH - SIDEBAR_X - 40
SIDEBAR_HEIGHT = MAP_HEIGHT

ACT_TWO_RENDER_SCALE = 2
ACT_TWO_VIEW_COLUMNS = 13
ACT_TWO_VIEW_ROWS = 9
ACT_TWO_VIEW_LOGICAL_WIDTH = ACT_TWO_VIEW_COLUMNS * TILE_SIZE
ACT_TWO_VIEW_LOGICAL_HEIGHT = ACT_TWO_VIEW_ROWS * TILE_SIZE
ACT_TWO_VIEW_X = 32
ACT_TWO_VIEW_Y = (
    GAME_HEIGHT
    - ACT_TWO_VIEW_LOGICAL_HEIGHT * ACT_TWO_RENDER_SCALE
) // 2
ACT_TWO_VIEW_WIDTH = ACT_TWO_VIEW_LOGICAL_WIDTH * ACT_TWO_RENDER_SCALE
ACT_TWO_VIEW_HEIGHT = ACT_TWO_VIEW_LOGICAL_HEIGHT * ACT_TWO_RENDER_SCALE

PROJECT_ROOT = Path(__file__).resolve().parent.parent
ASSET_ROOT = PROJECT_ROOT / "assets" / "sprites"
FONT_ROOT = PROJECT_ROOT / "assets" / "fonts"
AUDIO_ROOT = PROJECT_ROOT / "assets" / "audio"
ACT_THREE_MUSIC_PATH = AUDIO_ROOT / "music" / "act_3.mp3"

ACT_THREE_TILE_SIZE = 64
ACT_THREE_VIEW_X = 88
ACT_THREE_VIEW_Y = 104
ACT_THREE_VIEW_WIDTH = 768
ACT_THREE_VIEW_HEIGHT = 512
ACT_THREE_FRAME_X = 8
ACT_THREE_FRAME_Y = 32
ACT_THREE_SIDEBAR_X = 952
ACT_THREE_SIDEBAR_Y = 40
ACT_THREE_SIDEBAR_WIDTH = 304
ACT_THREE_SIDEBAR_HEIGHT = 640

AWAKENING_OPEN_START_MS = 300
AWAKENING_OPEN_END_MS = 1400
AWAKENING_HOLD_END_MS = 2000
AWAKENING_FADE_END_MS = 2800
AWAKENING_SECOND_OPEN_START_MS = 3300
AWAKENING_SECOND_OPEN_END_MS = 4700
AWAKENING_RECOVERY_BLINK_START_MS = 5150
AWAKENING_RECOVERY_BLINK_END_MS = 5750
AWAKENING_OLD_MAN_APPROACH_START_MS = 4700
AWAKENING_OLD_MAN_APPROACH_END_MS = 6500
AWAKENING_DIALOGUE_START_MS = 6500
CLASS_SELECTION_READY_MS = 16400
CLASS_SELECTION_CHOICE_END_MS = 2400

ACT_THREE_NARRATIVE_START_MS = 450
ACT_THREE_NARRATIVE_READY_MS = 10800
ACT_THREE_EYES_OPEN_START_MS = 500
ACT_THREE_EYES_OPEN_END_MS = 2400
ACT_THREE_CAMERA_END_MS = 4800
ACT_THREE_HANDS_RISE_START_MS = 3000
ACT_THREE_HANDS_RISE_END_MS = 6500
ACT_THREE_HANDS_HOLD_END_MS = 8500
ACT_THREE_CLENCH_END_MS = 9700
ACT_THREE_FINAL_HOLD_END_MS = 12800
ACT_THREE_AWAKENING_END_MS = 14500
