from game.attributes import PlayerBaseStats
ACT_THREE_VISION_RADIUS_TILES = 5
ACT_THREE_EXPLORED_FOG_ALPHA = 210
ACT_THREE_FOG_INNER_RADIUS_TILES = 1.25
ACT_THREE_FOG_OUTER_RADIUS_TILES = 4.0
ACT_THREE_CURRENT_REVEAL_ALPHA = 170

ASSASSIN_SHADOW_STEP_DURATION_MS = 800
ASSASSIN_TELEPORT_CHARGES = 3
ASSASSIN_ULTIMATE_CHARGES = 8
ASSASSIN_ULTIMATE_PRELUDE_MS = 400
ASSASSIN_ULTIMATE_STEP_MS = 1100
ASSASSIN_ULTIMATE_OUTRO_MS = 400
ASSASSIN_ULTIMATE_FINAL_IMPACT_MS = 760
ASSASSIN_ULTIMATE_CAMERA_TRAVEL_RATIO = 0.40
ASSASSIN_SHADOW_REFLEX_DAGGER_RELEASE_MS = 55
ASSASSIN_SHADOW_REFLEX_DAGGER_TRAVEL_MS = 320
ASSASSIN_SHADOW_REFLEX_DAGGER_IMPACT_MS = 130
ASSASSIN_SHADOW_REFLEX_LABEL_MS = 950
ASSASSIN_SHADOW_REFLEX_LABEL_RISE = 18

ARCHER_BASIC_ATTACK_RANGE = 2
ARCHER_BASIC_DAMAGE_MIN = 1
ARCHER_BASIC_DAMAGE_MAX = 2
ARCHER_EMPOWERED_SHOT_CHARGES = 3
ARCHER_EMPOWERED_SHOT_DAMAGE_MIN = 3
ARCHER_EMPOWERED_SHOT_DAMAGE_MAX = 5
ARCHER_EMPOWERED_SHOT_PROJECTILE_MS = 260
ARCHER_LEAP_CHARGES = 3
ARCHER_LEAP_RANGE = 3
ARCHER_LEAP_DURATION_MS = 320
ARCHER_BARRAGE_ZONE_CHARGES = 8
ARCHER_BARRAGE_ZONE_SIZE = 5

BERSERKER_RAGE_INJURED_HEALTH_RATIO = 0.50
BERSERKER_RAGE_CRITICAL_HEALTH_RATIO = 0.25
BERSERKER_RAGE_INJURED_DAMAGE_MULTIPLIER = 1.25
BERSERKER_RAGE_CRITICAL_DAMAGE_MULTIPLIER = 1.50
BERSERKER_CRUSHING_LEAP_CHARGES = 3
BERSERKER_CRUSHING_LEAP_RANGE = 5
BERSERKER_CRUSHING_LEAP_TRAVEL_MS = 500
BERSERKER_CRUSHING_LEAP_IMPACT_MS = 380
BERSERKER_LAST_RAGE_CHARGES = 8
BERSERKER_LAST_RAGE_TURNS = 10

PALADIN_HOLY_HAND_CHARGES = 3
PALADIN_HOLY_HAND_HEALING = 4
PALADIN_HOLY_HAND_EFFECT_MS = 650
PALADIN_SHIELD_CHARGE_CHARGES = 4
PALADIN_SHIELD_CHARGE_RANGE = 6
PALADIN_SHIELD_CHARGE_TRAVEL_MS = 420
PALADIN_HOLY_SHIELD_CHARGES = 8
PALADIN_HOLY_SHIELD_TURNS = 8
PALADIN_HOLY_SHIELD_DAMAGE_BONUS = 2
PALADIN_HOLY_SHIELD_HEALING_PER_HIT = 1

WARLOCK_BASIC_ATTACK_RANGE = 2
WARLOCK_BASIC_DAMAGE_MIN = 1
WARLOCK_BASIC_DAMAGE_MAX = 2
WARLOCK_DEMON_FORM_HEALTH_DRAIN = 1
WARLOCK_DEMON_FORM_DAMAGE_MULTIPLIER = 1.75
WARLOCK_CURSE_CHARGES = 3
WARLOCK_CURSE_TURNS = 10
WARLOCK_CURSE_RANGE = 5
WARLOCK_CURSE_DAMAGE_MULTIPLIER = 1.50
WARLOCK_SOUL_EXCHANGE_CHARGES = 4
WARLOCK_SOUL_EXCHANGE_RANGE = 5
WARLOCK_SOUL_EXCHANGE_TRAVEL_MS = 460

SUMMONER_FAMILIAR_CHARGES = 3
SUMMONER_ATTACK_RANGE = 2
SUMMONER_ATTACK_RANGE_WITH_FAMILIAR = 1
SUMMONER_BOND_CHARGES = 3
SUMMONER_BOND_DAMAGE_BONUS = 2
SUMMONER_TRUE_FORM_CHARGES = 5
SUMMONER_TRUE_FORM_HEALTH_BONUS = 8
SUMMONER_TRUE_FORM_DAMAGE_BONUS = 3

# Base stats for every Act Three subclass, excluding run upgrades.
# They currently match their parent classes and can be balanced independently.
SUBCLASS_BASE_STATS = {
    "berserker": PlayerBaseStats(
        max_health=16,
        damage_min=2,
        damage_max=3,
    ),
    "paladin": PlayerBaseStats(
        max_health=16,
        damage_min=2,
        damage_max=3,
    ),
    "assassin": PlayerBaseStats(
        max_health=10,
        damage_min=2,
        damage_max=3,
        crit_chance=0.10,
        dodge_chance=0.10,
    ),
    "archer": PlayerBaseStats(
        max_health=10,
        damage_min=2,
        damage_max=3,
        crit_chance=0.10,
        dodge_chance=0.10,
    ),
    "warlock": PlayerBaseStats(
        max_health=12,
        damage_min=2,
        damage_max=3,
    ),
    "summoner": PlayerBaseStats(
        max_health=12,
        damage_min=2,
        damage_max=3,
    ),
}

ACT_THREE_ENCOUNTER_SETTINGS = {
    1: {
        "enabled": False,
        "enemy_weights": {
            "archer": 4,
            "brute": 3,
            "sentinel": 2,
            "priest": 1,
        },
        "min_enemies": 0,
        "max_enemies": 0,
        "minimum_spacing": 2,
        "minimum_player_distance": 4,
    },
    2: {
        "enabled": True,
        "enemy_weights": {
            "archer": 4,
            "brute": 3,
            "sentinel": 2,
            "priest": 1,
        },
        "min_enemies": 1,
        "max_enemies": 3,
        "minimum_spacing": 2,
        "minimum_player_distance": 5,
    },
}